### ISSUE TITLE
ArrayIndexOutOfBound Exception

### ISSUE THREAD

**Issue by mahi05** [ceryle/FitGridView#1]
I am using (4 * 4) design for gridview but set only 15 data. It causes crash. How can i display 15 elements instead of 16 into (4*4) GridView?

**Comment by ceryle** [comment]
Hi,
Sorry, it is not possible. Data's size should be multiplies of two.

**Comment by ceryle** [comment]
Hi,
I have updated the library (v1.0.1) and you can now give the size of your data to adapter.

You can use like below.

```
int dataSize = 15;
Adapter(Context context) {
        super(context, R.layout.grid_item, dataSize);
        this.context = context;
}
```
